[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[functions."ais-vessels"]
  timeout_seconds = 15

[functions."test-vicpagers"]
  timeout_seconds = 26

[functions."vehicle-lookup"]
  timeout_seconds = 26


  schedule = "*/5 * * * *"

[functions."poll-vicpagers"]
  schedule = "*/1 * * * *"
